---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: opensuse
    image: docker.io/opensuse/leap:latest
    pre_build_image: yes

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: no

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
