---
- name: Get keyring file
  get_url:
    url: "{{ brave_keyring_url }}"
    dest: "{{ brave_keyring_file }}"

- name: Add Brave repository
  copy:
    content: "deb [signed-by={{ brave_keyring_file }} arch=amd64] {{ brave_repo_url }} stable main"
    dest: "{{ brave_repo_file }}"
    mode: 0644
  notify: apt update

- name: Make sure all handlers run
  meta: flush_handlers

- name: Install Brave Browser
  apt:
    name: "brave-browser{{ brave_channel_label[brave_channel] }}"
    state: present
