---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: yes
  - name: fedora
    image: docker.io/pycontribs/fedora:latest
    pre_build_image: yes

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: no

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
